### ISSUE TITLE
Plugin only work for english client!

### ISSUE THREAD

**Issue by Lusaca87** [danielbrenom/MonsterLootHunter#5]
Hello.

Im not sure how do adress this issue, but in short words:
Every time if i open this plugin window. its empty. Has zero data in it.
Doesnt matter if i search for an item or not.

After switch my Game to English it works. Is there a way how i can use it in an another game language? I dont want to be forced to use it in english..

Best regards and thanks for help.

![image](https://user-images.githubusercontent.com/17047430/225201993-c88e1a9c-fafa-448e-83c5-8d91fb313fd4.png)

**Comment by danielbrenom** [comment]
Hello!
I think this is really an internationalization issue.
I'm sad to know that you came across this problem.
I'll try my best to solve this problem, and let you know when it's done.
Sorry for the inconvenience and thanks for trying to use the plugin.
Regards.

**Comment by danielbrenom** [comment]
Hello,
Sorry for taking so long to solve this issue.
The new version of MLH will solve the problem you're having. Now it should work regardless of the language the game is in.
As soon as the update is live on Dalamud you'll be able to use the plugin.
Thanks for you patience.
Regards.

**Comment by SeleneBathory** [comment]
Hello,

It seems not completely solve.
There is a list, but plugin don't find information about loot. Probably because the source is only in English and can't find item's name in other language. 

Thanks for your work. 

![ffxiv_dx11_j1Ock1bwVe](https://user-images.githubusercontent.com/85290679/233840031-5811d038-f0c4-49f4-9525-3e6a9fae3ca8.jpg)

**Comment by danielbrenom** [comment]
Ah, that is indeed correct.
The wiki is only in english. Since the plugin grabs the info from the wiki and the name of the item is not in english, it cannot retrieve the information.
I'd have to add a separate source for this case, where the primary source cannot provide the information.

**Comment by danielbrenom** [comment]
Hello,
I have submitted a new version of MLH for Dalamud which I hope solves this issue where the information is not retrieved.
Now it should be able to get the information for the items you're searching even if your client is not in english.
I ask that when the update is available you report back if the issue was solved.
@SeleneBathory @Lusaca87 
Regards.

**Comment by Lusaca87** [comment]
Hello.

Sorry, it take a long time for me to reply, work issues!

It looks like it work out for me.
![image](https://user-images.githubusercontent.com/17047430/235336287-e4cec70e-7f6c-4825-a010-bca3d7694f6d.png)

The Information if there are something will shown (mostly in english but better then nothing)
So i can work niw. but maybe Selene have to say something about it from her side.

best regards.

**Comment by SeleneBathory** [comment]
Hello,

Update resolve the issue. Informations stay in English but it's not a big problem for me. 
Thanks for your work.
Regards

![ffxiv_dx11_U3dEoOiAyk](https://user-images.githubusercontent.com/85290679/235350943-9209f99d-fba8-48f6-b193-c24b8c399481.jpg)

**Comment by danielbrenom** [comment]
Great to know that it's now working.
The information unfortunately is in english since the plugin gets it from the Wiki.
I'll make a plan to in the future be able to have an internal source, or a way that the information can be internationalized.
Best regards and thanks for using the plugin!
